### PR TITLE
CODE RUB: Add unit test for Github pipeline

### PR DESCRIPTION
**Pull request by said-akram**
Adjusted unit tests to run test for GithubPipeline

### CODE REVIEW

**Comment by ShriHumrudha** [comment]
> I will wait for PR #13 to be approved before I update and publish this pull request.

It is merged now.

**Comment by hassanhabib** [comment]
@ShriHumrudha friendly reminder.

**Comment by ShriHumrudha** [comment]
> @ShriHumrudha friendly reminder.

Thank you for the ping again. I missed the first ping and then it is not easy to find the to-do.

**Comment by ShriHumrudha** [comment]
@said-akram We enhanced the standard to categorize and localize the dependency exceptions.

Read: https://github.com/ShriHumrudha/GitActionSharp/blob/main/GitActionSharp.Tests.Unit/Services/WorkflowServiceTests.Exceptions.cs

Example: https://github.com/ShriHumrudha/GitActionSharp/blob/main/GitActionSharp.Tests.Unit/Services/WorkflowServiceTests.Exceptions.cs

**Comment by hassanhabib** [comment]
Closing due to inactivity

**Pull request closed without merging**
