### PR TITLE
DATA: Added dependabot model to ADONET

### PR DESCRIPTION
**Pull request by menfra**

### CODE REVIEW

**Comment by menfra** [comment]
@hassanhabib I added dependabot model to help with the creation of its workflow.

**Comment by hassanhabib** [comment]
@menfra thank you for this.
Can you post in here a run and generation of the yaml file?

**Comment by menfra** [comment]
@hassanhabib as requested.

Run
image

Generated file in bin
image

**Comment by hassanhabib** [comment]
@menfra circling back to this.
If dependabot starts updating YAML how do we update our C# code to match?

**Comment by menfra** [comment]
@hassanhabib if an update to the dependabot YAML is determined, we need to update the dependabot model class in this project to target such changes in future versions. 

This also applies to the GitHub pipeline models. Maintenance to code is inevitable. I hope this helps.

**Comment by hassanhabib** [comment]
> @hassanhabib if an update to the dependabot YAML is determined, we need to update the dependabot model class in this project to target such changes in future versions.
> 
> This also applies to the GitHub pipeline models. Maintenance to code is inevitable. I hope this helps.

@menfra assume that the bot updated a version of dotnet from `7.0.1` to `7.0.2` the C# code for ADotNet is still going to be saying `7.0.1` right? because the bot is updating the YAML not the C# code. correct?

**Comment by menfra** [comment]
@hassanhabib yes that is correct. The c# code version doesn't change in the code by dependabot since the dependency scan happens inside the `*.csproj` and the GitHub action file (YAML). 

The version stated as seen here from the `ADotNet.Tests.Console.Program.cs` (see code section below.)  would serve as the initial version at the time of generating the workflow yaml (`github-pipelines.yaml`). However, dependabot would continue to scan for newer and compatible dependencies in the project to be updated going forward. There the version stated in the c# code doesn't matter.
image

**Comment by hassanhabib** [comment]
> @hassanhabib yes that is correct. The c# code version doesn't change in the code by dependabot since the dependency scan happens inside the `*.csproj` and the GitHub action file (YAML).
> 
> The version stated as seen here from the `ADotNet.Tests.Console.Program.cs` (see code section below.) would serve as the initial version at the time of generating the workflow yaml (`github-pipelines.yaml`). However, dependabot would continue to scan for newer and compatible dependencies in the project to be updated going forward. There the version stated in the c# code doesn't matter. image

@menfra that's a problem. C# code and YAML has to always be in sync.
If dependabot can't do that then that defeats the whole purpose of writing infrastructure code in C#.
it also puts the project at the risk of someone running the C# generator and overriding all the YAML updates dependabot has done.

Unless we can come up with a way to update C# code with latest libraries then generate the YAML out of that code - I don't see any good way of adding dependabot here.

**Comment by menfra** [comment]
@hassanhabib, why would someone run the c# generator again to override all the YAML after the first run? If this is how the generation of workflow files is currently designed, then I would say it's a design flaw.

The workflow YAML (`github-pipelines.yaml`) should be generated once and the dependency updates of components stated in it (DotNET, docker/actions, checkout/actions, etc) should be continuously monitored and updated by a dependency checker and updater such as dependabot.

With this said, Thanks for the great interaction on this subject.

**Pull request closed without merging**
